version: '3.9'
services:
  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  db-console:
    image: postgres:13.1-alpine
    command: psql -h db -U postgres crisp_dev
    depends_on:
      - db
    environment:
      PGPASSWORD: postgres
  web:
    build:
      context: ..
      dockerfile: containers/Dockerfile.dev
    depends_on:
      - db
    ports:
      - "4000:4000"
      - "4010:4010"
    volumes:
      - ..:/app
