FROM elixir:1.11.3-alpine

WORKDIR /app

#
# Install runtime dependencies
#
# Dependency     Required by
# -----------------------------------------
# gcc            argon2_elixir
# inotify-tools  phoenix: live reloading
# make           argon2_elixir
# musl-dev       argon2_elixir
# npm            phoenix: asset compilation
# tzdata         set timezone
#
RUN apk add --no-cache \
 gcc \
 inotify-tools \
 make \
 musl-dev \
 npm \
 tzdata

# Set local timezone
RUN ln -sf /usr/share/zoneinfo/Europe/Helsinki /etc/localtime \
 && echo "Europe/Helsinki" > /etc/timezone

# Install hex and rebar
RUN mix local.hex --force \
 && mix local.rebar --force

# Add shell profile
COPY containers/profile /root/.profile

CMD ["mix", "phx.server"]
